;; Example drone communication problem
(define (problem drones-prob)
    (:domain drones)
  (:objects d1 d2 - drone
	    c1 c2 c3 c4 c5 - location)
  (:init (at d1 c1)
	 (at d2 c2)
	 (commrange c1 c2)
	 (commrange c2 c3)
	 (commrange c3 c4)
	 (commrange c4 c5)
	 (commrange c5 c4)
	 (commrange c4 c3)
	 (commrange c3 c2)
	 (commrange c2 c1)
	 (accessible c1 c2)
	 (accessible c2 c3)
	 (accessible c3 c4)
	 (accessible c4 c5)
	 (accessible c5 c4)
	 (accessible c4 c3)
	 (accessible c3 c2)
	 (accessible c2 c1)
	 (= (total-cost) 0)
	 (= (cost-used d1) 0)
	 (= (cost-used d2) 0)
	 (= (cost c1 c2) 1)
	 (= (cost c2 c3) 1)
	 (= (cost c3 c4) 1)
	 (= (cost c4 c5) 1)
	 (= (cost c5 c4) 1)
	 (= (cost c4 c3) 1)
	 (= (cost c3 c2) 1)
	 (= (cost c2 c1) 1))
  (:goal (and (recorded d1 c5)
	      (at d1 c1))))
  (:metric (minimize total-cost)))
