(define (domain drones)
    (:requirements :typing) 
  (:types drone location)
  (:predicates (at ?d - drone ?l - location)
	       (commrange ?la - location ?lb - location)
	       (recorded ?d - drone ?l - location))
  (:derived (occupied ?l - location)
	    (exists (?d - drone)
		    (and (at ?d ?l))))
  (:derived (linked ?l - location)
	    (exists (?lo - location)
		    (and (occupied ?lo)
			 (or (commrange ?l ?lo) (commrange ?lo ?l)))))
  (:action move
	   :parameters (?d - drone ?la - location ?lb - location)
	   :precondition (and (at ?d ?la)
			      (not (occupied ?lb))
			      (linked ?lb))
	   :effect (and (not (at ?d ?la))
			(at ?d ?lb)))
  (:action record
	   :parameters (?d - drone ?l - location)
	   :precondition (at ?d ?l)
	   :effect (and (recorded ?d ?l))))
